## **Bidirectional Associative Memory(BAM)**

In [1]:
import numpy as np

class BAM(object):
    def __init__(self, m, n):
        
        self.row_count = m
        self.col_count = n
        self.weight_matrix = np.zeros((self.row_count, self.col_count))
                 
    def feedForward(self, inp):
        result = ( np.mat(inp) * np.mat(self.weight_matrix) ).tolist()[0]
        result = list(map(lambda x: 1 if x > 0 else -1, result))
        
        return result
    
    def feedBackward(self, output):
        result = (( np.mat(output) * (np.mat((self.weight_matrix)).T ))).tolist()[0]
        result = list(map(lambda x: 1 if x > 0 else -1, result))
        
        return result
        
    def train(self, inp, output):
        for i in range(len(inp)):
            sample_in = inp[i]
            sample_out = output[i]
            
            for r in range(self.row_count):
                for c in range(self.col_count):
                    self.weight_matrix[r][c] += sample_in[r] * sample_out[c]   
       
    def printweight_matrix(self):
        print(np.mat(self.weight_matrix))

In [2]:
input_mat = np.array([[1, 1, 1, 1, 1, 1],
                      [-1, -1, -1, -1, -1, -1],
                      [1, -1, -1, 1, 1, 1],
                      [1, 1, -1, -1, -1, -1]
                     ])

output_mat = np.array([[1, 1, 1],
                       [-1, -1, -1],
                       [-1, 1, 1],
                       [1, -1, 1]
                      ])

numRows = input_mat.shape[1]
numCols = output_mat.shape[1]

In [3]:
print("Input Matrix :")
print(input_mat)
print("\nOutput Matrix :")
print(output_mat)

Input Matrix :
[[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1]]

Output Matrix :
[[ 1  1  1]
 [-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]]


In [4]:
model = BAM(numRows, numCols)

In [5]:
# training
model.train(input_mat, output_mat)

print ("weight matrix:")
model.printweight_matrix()

weight matrix:
[[2. 2. 4.]
 [4. 0. 2.]
 [2. 2. 0.]
 [0. 4. 2.]
 [0. 4. 2.]
 [0. 4. 2.]]


In [7]:
#testing
for i in range(len(input_mat)):
    print("\nIteration ", i+1)
    print("-------------------------")
    x = input_mat[i]
    f = 1
    epoch = 1
    while(f == 1):
        print("\nepoch = ", epoch)
        print("\nOriginal x: ", *x)
        y = output_mat[i]
        print("Target y: ", *y)
        y_ = model.feedForward(x)
        print("y': ", *y)
        x_ = model.feedBackward(y_)
        print("x': ", *x_)
        if (np.array_equal(x, x_)):
            f = 0
        x = x_
        epoch += 1


Iteration  1
-------------------------

epoch =  1

Original x:  1 1 1 1 1 1
Target y:  1 1 1
y':  1 1 1
x':  1 1 1 1 1 1

Iteration  2
-------------------------

epoch =  1

Original x:  -1 -1 -1 -1 -1 -1
Target y:  -1 -1 -1
y':  -1 -1 -1
x':  -1 -1 -1 -1 -1 -1

Iteration  3
-------------------------

epoch =  1

Original x:  1 -1 -1 1 1 1
Target y:  -1 1 1
y':  -1 1 1
x':  1 -1 -1 1 1 1

Iteration  4
-------------------------

epoch =  1

Original x:  1 1 -1 -1 -1 -1
Target y:  1 -1 1
y':  1 -1 1
x':  -1 1 -1 -1 -1 -1

epoch =  2

Original x:  -1 1 -1 -1 -1 -1
Target y:  1 -1 1
y':  1 -1 1
x':  -1 -1 -1 -1 -1 -1

epoch =  3

Original x:  -1 -1 -1 -1 -1 -1
Target y:  1 -1 1
y':  1 -1 1
x':  -1 -1 -1 -1 -1 -1
